# http://module-build.sourceforge.net/META-spec.html
# #XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-FreeProxy
version:      0.01
version_from: lib/WWW/FreeProxy.pm
installdirs:  site
requires:
	LWP::Simpe:	0
	Exporter:	0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17

