---
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
installdirs: site
name: WWW::FreeProxy
requires:
  Exporter: 0
  LWP::Simple: 0
version: 0.02
version_from: lib/WWW/FreeProxy.pm
